seed1:
  build: .
  #image: badele/debian-cassandra
  hostname: seed1
  expose:
    - "7199"
    - "9160"

node1:
  build: .
  hostname: node1
  links:
      - seed1
  expose:
    - "7199"
    - "9160"

seed2:
  build: .
  #image: badele/debian-cassandra
  hostname: seed2
  links:
      - seed1
  expose:
    - "7199"
    - "9160"

node2:
  build: .
  #image: badele/debian-cassandra
  hostname: node1
  links:
      - seed2
  expose:
    - "7199"
    - "9160"

manager:
  build: ../debian-cassandra-opscenter/
  #image: badele/debian-cassandra-opscenter
  hostname: manager
  links:
      - seed1
      - seed2
      - node1
      - node2
  ports:
    - "8888:8888"


  #-D cassandra.storage_port=17000 -D cassandra.ssl_storage_port=17001 -D cassandra.native_transport_port=9042 -D cassandra.rpc_port=9160
